services:
  backend:
    build:
      context: ./backend
    container_name: option-pricing-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: option-pricing-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
