/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Option Pricing Lab API
 * HTTP API for the FITE7405 mini option pricer.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AmericanOptionRequest,
  ArithmeticAsianOptionRequest,
  ArithmeticBasketOptionRequest,
  EuropeanOptionRequest,
  GeometricAsianOptionRequest,
  GeometricBasketOptionRequest,
  HTTPValidationError,
  HealthResponse,
  ImpliedVolatilityRequest,
  ImpliedVolatilityResponse,
  KikoPutOptionRequest,
  KikoResultResponse,
  MonteCarloEstimateResponse,
  PriceResponse
} from './model';





/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: HealthResponse
  status: 200
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthHealthGetResponse = (healthHealthGetResponseSuccess)

export const getHealthHealthGetUrl = () => {




  return `/health`
}

export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {

  const res = await fetch(getHealthHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthHealthGetResponse
}





export const getHealthHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = unknown


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Price European
 */
export type priceEuropeanPricingEuropeanPostResponse200 = {
  data: PriceResponse
  status: 200
}

export type priceEuropeanPricingEuropeanPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceEuropeanPricingEuropeanPostResponseSuccess = (priceEuropeanPricingEuropeanPostResponse200) & {
  headers: Headers;
};
export type priceEuropeanPricingEuropeanPostResponseError = (priceEuropeanPricingEuropeanPostResponse422) & {
  headers: Headers;
};

export type priceEuropeanPricingEuropeanPostResponse = (priceEuropeanPricingEuropeanPostResponseSuccess | priceEuropeanPricingEuropeanPostResponseError)

export const getPriceEuropeanPricingEuropeanPostUrl = () => {




  return `/pricing/european`
}

export const priceEuropeanPricingEuropeanPost = async (europeanOptionRequest: EuropeanOptionRequest, options?: RequestInit): Promise<priceEuropeanPricingEuropeanPostResponse> => {

  const res = await fetch(getPriceEuropeanPricingEuropeanPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      europeanOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceEuropeanPricingEuropeanPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceEuropeanPricingEuropeanPostResponse
}




export const getPriceEuropeanPricingEuropeanPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceEuropeanPricingEuropeanPost>>, TError,{data: EuropeanOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceEuropeanPricingEuropeanPost>>, TError,{data: EuropeanOptionRequest}, TContext> => {

const mutationKey = ['priceEuropeanPricingEuropeanPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceEuropeanPricingEuropeanPost>>, {data: EuropeanOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceEuropeanPricingEuropeanPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceEuropeanPricingEuropeanPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceEuropeanPricingEuropeanPost>>>
    export type PriceEuropeanPricingEuropeanPostMutationBody = EuropeanOptionRequest
    export type PriceEuropeanPricingEuropeanPostMutationError = HTTPValidationError

    /**
 * @summary Price European
 */
export const usePriceEuropeanPricingEuropeanPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceEuropeanPricingEuropeanPost>>, TError,{data: EuropeanOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceEuropeanPricingEuropeanPost>>,
        TError,
        {data: EuropeanOptionRequest},
        TContext
      > => {
      return useMutation(getPriceEuropeanPricingEuropeanPostMutationOptions(options), queryClient);
    }

/**
 * @summary Solve Implied Volatility
 */
export type solveImpliedVolatilityPricingImpliedVolatilityPostResponse200 = {
  data: ImpliedVolatilityResponse
  status: 200
}

export type solveImpliedVolatilityPricingImpliedVolatilityPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type solveImpliedVolatilityPricingImpliedVolatilityPostResponseSuccess = (solveImpliedVolatilityPricingImpliedVolatilityPostResponse200) & {
  headers: Headers;
};
export type solveImpliedVolatilityPricingImpliedVolatilityPostResponseError = (solveImpliedVolatilityPricingImpliedVolatilityPostResponse422) & {
  headers: Headers;
};

export type solveImpliedVolatilityPricingImpliedVolatilityPostResponse = (solveImpliedVolatilityPricingImpliedVolatilityPostResponseSuccess | solveImpliedVolatilityPricingImpliedVolatilityPostResponseError)

export const getSolveImpliedVolatilityPricingImpliedVolatilityPostUrl = () => {




  return `/pricing/implied-volatility`
}

export const solveImpliedVolatilityPricingImpliedVolatilityPost = async (impliedVolatilityRequest: ImpliedVolatilityRequest, options?: RequestInit): Promise<solveImpliedVolatilityPricingImpliedVolatilityPostResponse> => {

  const res = await fetch(getSolveImpliedVolatilityPricingImpliedVolatilityPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      impliedVolatilityRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: solveImpliedVolatilityPricingImpliedVolatilityPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as solveImpliedVolatilityPricingImpliedVolatilityPostResponse
}




export const getSolveImpliedVolatilityPricingImpliedVolatilityPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof solveImpliedVolatilityPricingImpliedVolatilityPost>>, TError,{data: ImpliedVolatilityRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof solveImpliedVolatilityPricingImpliedVolatilityPost>>, TError,{data: ImpliedVolatilityRequest}, TContext> => {

const mutationKey = ['solveImpliedVolatilityPricingImpliedVolatilityPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof solveImpliedVolatilityPricingImpliedVolatilityPost>>, {data: ImpliedVolatilityRequest}> = (props) => {
          const {data} = props ?? {};

          return  solveImpliedVolatilityPricingImpliedVolatilityPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SolveImpliedVolatilityPricingImpliedVolatilityPostMutationResult = NonNullable<Awaited<ReturnType<typeof solveImpliedVolatilityPricingImpliedVolatilityPost>>>
    export type SolveImpliedVolatilityPricingImpliedVolatilityPostMutationBody = ImpliedVolatilityRequest
    export type SolveImpliedVolatilityPricingImpliedVolatilityPostMutationError = HTTPValidationError

    /**
 * @summary Solve Implied Volatility
 */
export const useSolveImpliedVolatilityPricingImpliedVolatilityPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof solveImpliedVolatilityPricingImpliedVolatilityPost>>, TError,{data: ImpliedVolatilityRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof solveImpliedVolatilityPricingImpliedVolatilityPost>>,
        TError,
        {data: ImpliedVolatilityRequest},
        TContext
      > => {
      return useMutation(getSolveImpliedVolatilityPricingImpliedVolatilityPostMutationOptions(options), queryClient);
    }

/**
 * @summary Price American
 */
export type priceAmericanPricingAmericanPostResponse200 = {
  data: PriceResponse
  status: 200
}

export type priceAmericanPricingAmericanPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceAmericanPricingAmericanPostResponseSuccess = (priceAmericanPricingAmericanPostResponse200) & {
  headers: Headers;
};
export type priceAmericanPricingAmericanPostResponseError = (priceAmericanPricingAmericanPostResponse422) & {
  headers: Headers;
};

export type priceAmericanPricingAmericanPostResponse = (priceAmericanPricingAmericanPostResponseSuccess | priceAmericanPricingAmericanPostResponseError)

export const getPriceAmericanPricingAmericanPostUrl = () => {




  return `/pricing/american`
}

export const priceAmericanPricingAmericanPost = async (americanOptionRequest: AmericanOptionRequest, options?: RequestInit): Promise<priceAmericanPricingAmericanPostResponse> => {

  const res = await fetch(getPriceAmericanPricingAmericanPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      americanOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceAmericanPricingAmericanPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceAmericanPricingAmericanPostResponse
}




export const getPriceAmericanPricingAmericanPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceAmericanPricingAmericanPost>>, TError,{data: AmericanOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceAmericanPricingAmericanPost>>, TError,{data: AmericanOptionRequest}, TContext> => {

const mutationKey = ['priceAmericanPricingAmericanPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceAmericanPricingAmericanPost>>, {data: AmericanOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceAmericanPricingAmericanPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceAmericanPricingAmericanPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceAmericanPricingAmericanPost>>>
    export type PriceAmericanPricingAmericanPostMutationBody = AmericanOptionRequest
    export type PriceAmericanPricingAmericanPostMutationError = HTTPValidationError

    /**
 * @summary Price American
 */
export const usePriceAmericanPricingAmericanPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceAmericanPricingAmericanPost>>, TError,{data: AmericanOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceAmericanPricingAmericanPost>>,
        TError,
        {data: AmericanOptionRequest},
        TContext
      > => {
      return useMutation(getPriceAmericanPricingAmericanPostMutationOptions(options), queryClient);
    }

/**
 * @summary Price Geometric Asian
 */
export type priceGeometricAsianPricingAsianGeometricPostResponse200 = {
  data: PriceResponse
  status: 200
}

export type priceGeometricAsianPricingAsianGeometricPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceGeometricAsianPricingAsianGeometricPostResponseSuccess = (priceGeometricAsianPricingAsianGeometricPostResponse200) & {
  headers: Headers;
};
export type priceGeometricAsianPricingAsianGeometricPostResponseError = (priceGeometricAsianPricingAsianGeometricPostResponse422) & {
  headers: Headers;
};

export type priceGeometricAsianPricingAsianGeometricPostResponse = (priceGeometricAsianPricingAsianGeometricPostResponseSuccess | priceGeometricAsianPricingAsianGeometricPostResponseError)

export const getPriceGeometricAsianPricingAsianGeometricPostUrl = () => {




  return `/pricing/asian/geometric`
}

export const priceGeometricAsianPricingAsianGeometricPost = async (geometricAsianOptionRequest: GeometricAsianOptionRequest, options?: RequestInit): Promise<priceGeometricAsianPricingAsianGeometricPostResponse> => {

  const res = await fetch(getPriceGeometricAsianPricingAsianGeometricPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      geometricAsianOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceGeometricAsianPricingAsianGeometricPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceGeometricAsianPricingAsianGeometricPostResponse
}




export const getPriceGeometricAsianPricingAsianGeometricPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceGeometricAsianPricingAsianGeometricPost>>, TError,{data: GeometricAsianOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceGeometricAsianPricingAsianGeometricPost>>, TError,{data: GeometricAsianOptionRequest}, TContext> => {

const mutationKey = ['priceGeometricAsianPricingAsianGeometricPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceGeometricAsianPricingAsianGeometricPost>>, {data: GeometricAsianOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceGeometricAsianPricingAsianGeometricPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceGeometricAsianPricingAsianGeometricPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceGeometricAsianPricingAsianGeometricPost>>>
    export type PriceGeometricAsianPricingAsianGeometricPostMutationBody = GeometricAsianOptionRequest
    export type PriceGeometricAsianPricingAsianGeometricPostMutationError = HTTPValidationError

    /**
 * @summary Price Geometric Asian
 */
export const usePriceGeometricAsianPricingAsianGeometricPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceGeometricAsianPricingAsianGeometricPost>>, TError,{data: GeometricAsianOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceGeometricAsianPricingAsianGeometricPost>>,
        TError,
        {data: GeometricAsianOptionRequest},
        TContext
      > => {
      return useMutation(getPriceGeometricAsianPricingAsianGeometricPostMutationOptions(options), queryClient);
    }

/**
 * @summary Price Arithmetic Asian
 */
export type priceArithmeticAsianPricingAsianArithmeticPostResponse200 = {
  data: MonteCarloEstimateResponse
  status: 200
}

export type priceArithmeticAsianPricingAsianArithmeticPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceArithmeticAsianPricingAsianArithmeticPostResponseSuccess = (priceArithmeticAsianPricingAsianArithmeticPostResponse200) & {
  headers: Headers;
};
export type priceArithmeticAsianPricingAsianArithmeticPostResponseError = (priceArithmeticAsianPricingAsianArithmeticPostResponse422) & {
  headers: Headers;
};

export type priceArithmeticAsianPricingAsianArithmeticPostResponse = (priceArithmeticAsianPricingAsianArithmeticPostResponseSuccess | priceArithmeticAsianPricingAsianArithmeticPostResponseError)

export const getPriceArithmeticAsianPricingAsianArithmeticPostUrl = () => {




  return `/pricing/asian/arithmetic`
}

export const priceArithmeticAsianPricingAsianArithmeticPost = async (arithmeticAsianOptionRequest: ArithmeticAsianOptionRequest, options?: RequestInit): Promise<priceArithmeticAsianPricingAsianArithmeticPostResponse> => {

  const res = await fetch(getPriceArithmeticAsianPricingAsianArithmeticPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      arithmeticAsianOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceArithmeticAsianPricingAsianArithmeticPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceArithmeticAsianPricingAsianArithmeticPostResponse
}




export const getPriceArithmeticAsianPricingAsianArithmeticPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceArithmeticAsianPricingAsianArithmeticPost>>, TError,{data: ArithmeticAsianOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceArithmeticAsianPricingAsianArithmeticPost>>, TError,{data: ArithmeticAsianOptionRequest}, TContext> => {

const mutationKey = ['priceArithmeticAsianPricingAsianArithmeticPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceArithmeticAsianPricingAsianArithmeticPost>>, {data: ArithmeticAsianOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceArithmeticAsianPricingAsianArithmeticPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceArithmeticAsianPricingAsianArithmeticPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceArithmeticAsianPricingAsianArithmeticPost>>>
    export type PriceArithmeticAsianPricingAsianArithmeticPostMutationBody = ArithmeticAsianOptionRequest
    export type PriceArithmeticAsianPricingAsianArithmeticPostMutationError = HTTPValidationError

    /**
 * @summary Price Arithmetic Asian
 */
export const usePriceArithmeticAsianPricingAsianArithmeticPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceArithmeticAsianPricingAsianArithmeticPost>>, TError,{data: ArithmeticAsianOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceArithmeticAsianPricingAsianArithmeticPost>>,
        TError,
        {data: ArithmeticAsianOptionRequest},
        TContext
      > => {
      return useMutation(getPriceArithmeticAsianPricingAsianArithmeticPostMutationOptions(options), queryClient);
    }

/**
 * @summary Price Geometric Basket
 */
export type priceGeometricBasketPricingBasketGeometricPostResponse200 = {
  data: PriceResponse
  status: 200
}

export type priceGeometricBasketPricingBasketGeometricPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceGeometricBasketPricingBasketGeometricPostResponseSuccess = (priceGeometricBasketPricingBasketGeometricPostResponse200) & {
  headers: Headers;
};
export type priceGeometricBasketPricingBasketGeometricPostResponseError = (priceGeometricBasketPricingBasketGeometricPostResponse422) & {
  headers: Headers;
};

export type priceGeometricBasketPricingBasketGeometricPostResponse = (priceGeometricBasketPricingBasketGeometricPostResponseSuccess | priceGeometricBasketPricingBasketGeometricPostResponseError)

export const getPriceGeometricBasketPricingBasketGeometricPostUrl = () => {




  return `/pricing/basket/geometric`
}

export const priceGeometricBasketPricingBasketGeometricPost = async (geometricBasketOptionRequest: GeometricBasketOptionRequest, options?: RequestInit): Promise<priceGeometricBasketPricingBasketGeometricPostResponse> => {

  const res = await fetch(getPriceGeometricBasketPricingBasketGeometricPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      geometricBasketOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceGeometricBasketPricingBasketGeometricPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceGeometricBasketPricingBasketGeometricPostResponse
}




export const getPriceGeometricBasketPricingBasketGeometricPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceGeometricBasketPricingBasketGeometricPost>>, TError,{data: GeometricBasketOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceGeometricBasketPricingBasketGeometricPost>>, TError,{data: GeometricBasketOptionRequest}, TContext> => {

const mutationKey = ['priceGeometricBasketPricingBasketGeometricPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceGeometricBasketPricingBasketGeometricPost>>, {data: GeometricBasketOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceGeometricBasketPricingBasketGeometricPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceGeometricBasketPricingBasketGeometricPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceGeometricBasketPricingBasketGeometricPost>>>
    export type PriceGeometricBasketPricingBasketGeometricPostMutationBody = GeometricBasketOptionRequest
    export type PriceGeometricBasketPricingBasketGeometricPostMutationError = HTTPValidationError

    /**
 * @summary Price Geometric Basket
 */
export const usePriceGeometricBasketPricingBasketGeometricPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceGeometricBasketPricingBasketGeometricPost>>, TError,{data: GeometricBasketOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceGeometricBasketPricingBasketGeometricPost>>,
        TError,
        {data: GeometricBasketOptionRequest},
        TContext
      > => {
      return useMutation(getPriceGeometricBasketPricingBasketGeometricPostMutationOptions(options), queryClient);
    }

/**
 * @summary Price Arithmetic Basket
 */
export type priceArithmeticBasketPricingBasketArithmeticPostResponse200 = {
  data: MonteCarloEstimateResponse
  status: 200
}

export type priceArithmeticBasketPricingBasketArithmeticPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceArithmeticBasketPricingBasketArithmeticPostResponseSuccess = (priceArithmeticBasketPricingBasketArithmeticPostResponse200) & {
  headers: Headers;
};
export type priceArithmeticBasketPricingBasketArithmeticPostResponseError = (priceArithmeticBasketPricingBasketArithmeticPostResponse422) & {
  headers: Headers;
};

export type priceArithmeticBasketPricingBasketArithmeticPostResponse = (priceArithmeticBasketPricingBasketArithmeticPostResponseSuccess | priceArithmeticBasketPricingBasketArithmeticPostResponseError)

export const getPriceArithmeticBasketPricingBasketArithmeticPostUrl = () => {




  return `/pricing/basket/arithmetic`
}

export const priceArithmeticBasketPricingBasketArithmeticPost = async (arithmeticBasketOptionRequest: ArithmeticBasketOptionRequest, options?: RequestInit): Promise<priceArithmeticBasketPricingBasketArithmeticPostResponse> => {

  const res = await fetch(getPriceArithmeticBasketPricingBasketArithmeticPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      arithmeticBasketOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceArithmeticBasketPricingBasketArithmeticPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceArithmeticBasketPricingBasketArithmeticPostResponse
}




export const getPriceArithmeticBasketPricingBasketArithmeticPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceArithmeticBasketPricingBasketArithmeticPost>>, TError,{data: ArithmeticBasketOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceArithmeticBasketPricingBasketArithmeticPost>>, TError,{data: ArithmeticBasketOptionRequest}, TContext> => {

const mutationKey = ['priceArithmeticBasketPricingBasketArithmeticPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceArithmeticBasketPricingBasketArithmeticPost>>, {data: ArithmeticBasketOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceArithmeticBasketPricingBasketArithmeticPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceArithmeticBasketPricingBasketArithmeticPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceArithmeticBasketPricingBasketArithmeticPost>>>
    export type PriceArithmeticBasketPricingBasketArithmeticPostMutationBody = ArithmeticBasketOptionRequest
    export type PriceArithmeticBasketPricingBasketArithmeticPostMutationError = HTTPValidationError

    /**
 * @summary Price Arithmetic Basket
 */
export const usePriceArithmeticBasketPricingBasketArithmeticPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceArithmeticBasketPricingBasketArithmeticPost>>, TError,{data: ArithmeticBasketOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceArithmeticBasketPricingBasketArithmeticPost>>,
        TError,
        {data: ArithmeticBasketOptionRequest},
        TContext
      > => {
      return useMutation(getPriceArithmeticBasketPricingBasketArithmeticPostMutationOptions(options), queryClient);
    }

/**
 * @summary Price Kiko Put
 */
export type priceKikoPutPricingKikoPutPostResponse200 = {
  data: KikoResultResponse
  status: 200
}

export type priceKikoPutPricingKikoPutPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type priceKikoPutPricingKikoPutPostResponseSuccess = (priceKikoPutPricingKikoPutPostResponse200) & {
  headers: Headers;
};
export type priceKikoPutPricingKikoPutPostResponseError = (priceKikoPutPricingKikoPutPostResponse422) & {
  headers: Headers;
};

export type priceKikoPutPricingKikoPutPostResponse = (priceKikoPutPricingKikoPutPostResponseSuccess | priceKikoPutPricingKikoPutPostResponseError)

export const getPriceKikoPutPricingKikoPutPostUrl = () => {




  return `/pricing/kiko-put`
}

export const priceKikoPutPricingKikoPutPost = async (kikoPutOptionRequest: KikoPutOptionRequest, options?: RequestInit): Promise<priceKikoPutPricingKikoPutPostResponse> => {

  const res = await fetch(getPriceKikoPutPricingKikoPutPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kikoPutOptionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: priceKikoPutPricingKikoPutPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as priceKikoPutPricingKikoPutPostResponse
}




export const getPriceKikoPutPricingKikoPutPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceKikoPutPricingKikoPutPost>>, TError,{data: KikoPutOptionRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof priceKikoPutPricingKikoPutPost>>, TError,{data: KikoPutOptionRequest}, TContext> => {

const mutationKey = ['priceKikoPutPricingKikoPutPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof priceKikoPutPricingKikoPutPost>>, {data: KikoPutOptionRequest}> = (props) => {
          const {data} = props ?? {};

          return  priceKikoPutPricingKikoPutPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PriceKikoPutPricingKikoPutPostMutationResult = NonNullable<Awaited<ReturnType<typeof priceKikoPutPricingKikoPutPost>>>
    export type PriceKikoPutPricingKikoPutPostMutationBody = KikoPutOptionRequest
    export type PriceKikoPutPricingKikoPutPostMutationError = HTTPValidationError

    /**
 * @summary Price Kiko Put
 */
export const usePriceKikoPutPricingKikoPutPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof priceKikoPutPricingKikoPutPost>>, TError,{data: KikoPutOptionRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof priceKikoPutPricingKikoPutPost>>,
        TError,
        {data: KikoPutOptionRequest},
        TContext
      > => {
      return useMutation(getPriceKikoPutPricingKikoPutPostMutationOptions(options), queryClient);
    }

