/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Option Pricing Lab API
 * HTTP API for the FITE7405 mini option pricer.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker/locale/en';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HealthResponse,
  ImpliedVolatilityResponse,
  KikoResultResponse,
  MonteCarloEstimateResponse,
  PriceResponse
} from './model';


export const getHealthHealthGetResponseMock = (overrideResponse: Partial<Extract<HealthResponse, object>> = {}): HealthResponse => ({status: faker.string.alpha({length: {min: 10, max: 20}}), service: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getPriceEuropeanPricingEuropeanPostResponseMock = (overrideResponse: Partial<Extract<PriceResponse, object>> = {}): PriceResponse => ({price: faker.number.float({fractionDigits: 2}), ...overrideResponse})

export const getSolveImpliedVolatilityPricingImpliedVolatilityPostResponseMock = (overrideResponse: Partial<Extract<ImpliedVolatilityResponse, object>> = {}): ImpliedVolatilityResponse => ({implied_volatility: faker.number.float({fractionDigits: 2}), ...overrideResponse})

export const getPriceAmericanPricingAmericanPostResponseMock = (overrideResponse: Partial<Extract<PriceResponse, object>> = {}): PriceResponse => ({price: faker.number.float({fractionDigits: 2}), ...overrideResponse})

export const getPriceGeometricAsianPricingAsianGeometricPostResponseMock = (overrideResponse: Partial<Extract<PriceResponse, object>> = {}): PriceResponse => ({price: faker.number.float({fractionDigits: 2}), ...overrideResponse})

export const getPriceArithmeticAsianPricingAsianArithmeticPostResponseMock = (overrideResponse: Partial<Extract<MonteCarloEstimateResponse, object>> = {}): MonteCarloEstimateResponse => ({price: faker.number.float({fractionDigits: 2}), std_error: faker.number.float({fractionDigits: 2}), confidence_interval: {lower: faker.number.float({fractionDigits: 2}), upper: faker.number.float({fractionDigits: 2})}, ...overrideResponse})

export const getPriceGeometricBasketPricingBasketGeometricPostResponseMock = (overrideResponse: Partial<Extract<PriceResponse, object>> = {}): PriceResponse => ({price: faker.number.float({fractionDigits: 2}), ...overrideResponse})

export const getPriceArithmeticBasketPricingBasketArithmeticPostResponseMock = (overrideResponse: Partial<Extract<MonteCarloEstimateResponse, object>> = {}): MonteCarloEstimateResponse => ({price: faker.number.float({fractionDigits: 2}), std_error: faker.number.float({fractionDigits: 2}), confidence_interval: {lower: faker.number.float({fractionDigits: 2}), upper: faker.number.float({fractionDigits: 2})}, ...overrideResponse})

export const getPriceKikoPutPricingKikoPutPostResponseMock = (overrideResponse: Partial<Extract<KikoResultResponse, object>> = {}): KikoResultResponse => ({price: faker.number.float({fractionDigits: 2}), delta: faker.number.float({fractionDigits: 2}), std_error: faker.number.float({fractionDigits: 2}), confidence_interval: {lower: faker.number.float({fractionDigits: 2}), upper: faker.number.float({fractionDigits: 2})}, ...overrideResponse})


export const getHealthHealthGetMockHandler = (overrideResponse?: HealthResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthResponse> | HealthResponse), options?: RequestHandlerOptions) => {
  return http.get('/health', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthHealthGetResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceEuropeanPricingEuropeanPostMockHandler = (overrideResponse?: PriceResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PriceResponse> | PriceResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/european', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceEuropeanPricingEuropeanPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSolveImpliedVolatilityPricingImpliedVolatilityPostMockHandler = (overrideResponse?: ImpliedVolatilityResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ImpliedVolatilityResponse> | ImpliedVolatilityResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/implied-volatility', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSolveImpliedVolatilityPricingImpliedVolatilityPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceAmericanPricingAmericanPostMockHandler = (overrideResponse?: PriceResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PriceResponse> | PriceResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/american', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceAmericanPricingAmericanPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceGeometricAsianPricingAsianGeometricPostMockHandler = (overrideResponse?: PriceResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PriceResponse> | PriceResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/asian/geometric', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceGeometricAsianPricingAsianGeometricPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceArithmeticAsianPricingAsianArithmeticPostMockHandler = (overrideResponse?: MonteCarloEstimateResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MonteCarloEstimateResponse> | MonteCarloEstimateResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/asian/arithmetic', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceArithmeticAsianPricingAsianArithmeticPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceGeometricBasketPricingBasketGeometricPostMockHandler = (overrideResponse?: PriceResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PriceResponse> | PriceResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/basket/geometric', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceGeometricBasketPricingBasketGeometricPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceArithmeticBasketPricingBasketArithmeticPostMockHandler = (overrideResponse?: MonteCarloEstimateResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MonteCarloEstimateResponse> | MonteCarloEstimateResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/basket/arithmetic', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceArithmeticBasketPricingBasketArithmeticPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPriceKikoPutPricingKikoPutPostMockHandler = (overrideResponse?: KikoResultResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<KikoResultResponse> | KikoResultResponse), options?: RequestHandlerOptions) => {
  return http.post('/pricing/kiko-put', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {await delay(1000);


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPriceKikoPutPricingKikoPutPostResponseMock(),
      { status: 200
      })
  }, options)
}
export const getOptionPricingLabAPIMock = () => [
  getHealthHealthGetMockHandler(),
  getPriceEuropeanPricingEuropeanPostMockHandler(),
  getSolveImpliedVolatilityPricingImpliedVolatilityPostMockHandler(),
  getPriceAmericanPricingAmericanPostMockHandler(),
  getPriceGeometricAsianPricingAsianGeometricPostMockHandler(),
  getPriceArithmeticAsianPricingAsianArithmeticPostMockHandler(),
  getPriceGeometricBasketPricingBasketGeometricPostMockHandler(),
  getPriceArithmeticBasketPricingBasketArithmeticPostMockHandler(),
  getPriceKikoPutPricingKikoPutPostMockHandler()
]
