/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Option Pricing Lab API
 * HTTP API for the FITE7405 mini option pricer.
 * OpenAPI spec version: 0.1.0
 */
import type { ConfidenceIntervalResponse } from './confidenceIntervalResponse';

export interface MonteCarloEstimateResponse {
  price: number;
  std_error: number;
  confidence_interval: ConfidenceIntervalResponse;
}
