/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Option Pricing Lab API
 * HTTP API for the FITE7405 mini option pricer.
 * OpenAPI spec version: 0.1.0
 */

export type OptionType = typeof OptionType[keyof typeof OptionType];


export const OptionType = {
  call: 'call',
  put: 'put',
} as const;
